name: Functions
on:
    pull_request:
    workflow_dispatch:

jobs:
    test-fuctions:
        runs-on: ubuntu-latest
        steps:
            - name: failing step
              run: exit 1
            - name: I will be skipped
              if: ${{ success() }}
              run: echo "This step will be skipped because the previous step failed."
            - name: I will run executed
              if: ${{ failure() }}
              run: echo "This step runs because the previous step failed."
            - name: I will be execute
              if: ${{ !cancelled() }}
              run: echo "I will always execute except when the workflow is cancelled."
            - name: Check for cancelled
              if: ${{ cancelled() }}
              run: echo "This step runs only if the workflow is cancelled."