name: Workflow runners
on: 
  push:

jobs:
    workflow-runner-job:
        runs-on: ubuntu-latest # here runs-on is used to define the type of runner on which the job will run, it is often called as runner specification.
        steps:
          - name: Show OS Information
            run: echo "This workflow runs on ${{ runner.os }} runner!"
    workflow-runner-job2:
        runs-on: windows-latest
        steps:
          - name: Show OS Information
            run: echo "This workflow runs on ${{ runner.os }} runner!"