name: context
run-name: Context|Debug- ${{ inputs.debug }} #
on:
  push:
  workflow_dispatch: #workflow_dispatch allows you to manually trigger a workflow run.
    inputs: #inputs allow you to define parameters that can be passed to the workflow when it is manually triggered.
        debug: #input parameter named debug
            type: boolean #type of the input parameter is boolean
            default: false #default value is false

jobs:
    show-context:
        runs-on: ubuntu-latest
        steps:
          - name: Show GitHub Context
            run: |
              echo "Repository: ${{ github.repository }}"
              echo "Ref: ${{ github.ref }}"
              echo "SHA: ${{ github.sha }}"
              echo "Actor: ${{ github.actor }}"
              echo "Event Name: ${{ github.event_name }}"
              echo "Workflow: ${{ github.workflow }}"
              echo "Job: ${{ github.job }}"
              echo "Run ID: ${{ github.run_id }}"
              echo "Run Number: ${{ github.run_number }}"
          - name: Retrive variables
            run: |
                echo "var1 is ${{ vars.var1 }}"
